# Generated by Django 3.2.7 on 2021-11-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bonus_scores',
            field=models.IntegerField(default=0),
        ),
    ]
