# Generated by Django 3.2.7 on 2021-09-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivering',
            field=models.BooleanField(default=False),
        ),
    ]
