# Generated by Django 3.2.7 on 2021-09-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_delivering'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('not taken', 'Свободен'), ('completed', 'Завершен'), ('delivering', 'В пути')], default='not taken', max_length=10),
        ),
    ]
