# Generated by Django 3.2.7 on 2021-10-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale',
            field=models.IntegerField(blank=True, default=0, verbose_name='Скидка в процентах'),
        ),
    ]
